version: '3.8'
services:
    php-apache:
        container_name: vsnippet-o-level1-classic
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
